// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository.go -destination=./internal/domain/mock/repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	models "go-gophkeeper/internal/models"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthRepository is a mock of AuthRepository interface.
type MockAuthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepositoryMockRecorder
	isgomock struct{}
}

// MockAuthRepositoryMockRecorder is the mock recorder for MockAuthRepository.
type MockAuthRepositoryMockRecorder struct {
	mock *MockAuthRepository
}

// NewMockAuthRepository creates a new mock instance.
func NewMockAuthRepository(ctrl *gomock.Controller) *MockAuthRepository {
	mock := &MockAuthRepository{ctrl: ctrl}
	mock.recorder = &MockAuthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRepository) EXPECT() *MockAuthRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuthRepository) Create(ctx context.Context, user *models.User) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAuthRepositoryMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuthRepository)(nil).Create), ctx, user)
}

// GetByLogin mocks base method.
func (m *MockAuthRepository) GetByLogin(ctx context.Context, login string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLogin", ctx, login)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLogin indicates an expected call of GetByLogin.
func (mr *MockAuthRepositoryMockRecorder) GetByLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLogin", reflect.TypeOf((*MockAuthRepository)(nil).GetByLogin), ctx, login)
}

// IsExist mocks base method.
func (m *MockAuthRepository) IsExist(ctx context.Context, login string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExist", ctx, login)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsExist indicates an expected call of IsExist.
func (mr *MockAuthRepositoryMockRecorder) IsExist(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExist", reflect.TypeOf((*MockAuthRepository)(nil).IsExist), ctx, login)
}

// MockVaultRepository is a mock of VaultRepository interface.
type MockVaultRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVaultRepositoryMockRecorder
	isgomock struct{}
}

// MockVaultRepositoryMockRecorder is the mock recorder for MockVaultRepository.
type MockVaultRepositoryMockRecorder struct {
	mock *MockVaultRepository
}

// NewMockVaultRepository creates a new mock instance.
func NewMockVaultRepository(ctrl *gomock.Controller) *MockVaultRepository {
	mock := &MockVaultRepository{ctrl: ctrl}
	mock.recorder = &MockVaultRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVaultRepository) EXPECT() *MockVaultRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockVaultRepository) Add(ctx context.Context, vaultObject models.VaultObject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, vaultObject)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockVaultRepositoryMockRecorder) Add(ctx, vaultObject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockVaultRepository)(nil).Add), ctx, vaultObject)
}

// AddList mocks base method.
func (m *MockVaultRepository) AddList(ctx context.Context, vaultObjects models.VaultObjects) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddList", ctx, vaultObjects)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddList indicates an expected call of AddList.
func (mr *MockVaultRepositoryMockRecorder) AddList(ctx, vaultObjects any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddList", reflect.TypeOf((*MockVaultRepository)(nil).AddList), ctx, vaultObjects)
}

// Get mocks base method.
func (m *MockVaultRepository) Get(ctx context.Context, name, login, dataType string) (models.VaultObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, name, login, dataType)
	ret0, _ := ret[0].(models.VaultObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVaultRepositoryMockRecorder) Get(ctx, name, login, dataType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVaultRepository)(nil).Get), ctx, name, login, dataType)
}

// GetDataToSync mocks base method.
func (m *MockVaultRepository) GetDataToSync(ctx context.Context, login string) (models.VaultObjects, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataToSync", ctx, login)
	ret0, _ := ret[0].(models.VaultObjects)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataToSync indicates an expected call of GetDataToSync.
func (mr *MockVaultRepositoryMockRecorder) GetDataToSync(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataToSync", reflect.TypeOf((*MockVaultRepository)(nil).GetDataToSync), ctx, login)
}

// IsExist mocks base method.
func (m *MockVaultRepository) IsExist(ctx context.Context, name, login string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExist", ctx, name, login)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsExist indicates an expected call of IsExist.
func (mr *MockVaultRepositoryMockRecorder) IsExist(ctx, name, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExist", reflect.TypeOf((*MockVaultRepository)(nil).IsExist), ctx, name, login)
}

// MockEventRepository is a mock of EventRepository interface.
type MockEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEventRepositoryMockRecorder
	isgomock struct{}
}

// MockEventRepositoryMockRecorder is the mock recorder for MockEventRepository.
type MockEventRepositoryMockRecorder struct {
	mock *MockEventRepository
}

// NewMockEventRepository creates a new mock instance.
func NewMockEventRepository(ctrl *gomock.Controller) *MockEventRepository {
	mock := &MockEventRepository{ctrl: ctrl}
	mock.recorder = &MockEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRepository) EXPECT() *MockEventRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockEventRepository) Add(ctx context.Context, login string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, login)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockEventRepositoryMockRecorder) Add(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockEventRepository)(nil).Add), ctx, login)
}

// Get mocks base method.
func (m *MockEventRepository) Get(ctx context.Context, login string) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, login)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockEventRepositoryMockRecorder) Get(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockEventRepository)(nil).Get), ctx, login)
}
