// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/file.proto

package file

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFileSizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileSizeRequest) Reset() {
	*x = GetFileSizeRequest{}
	mi := &file_proto_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileSizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileSizeRequest) ProtoMessage() {}

func (x *GetFileSizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileSizeRequest.ProtoReflect.Descriptor instead.
func (*GetFileSizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_proto_rawDescGZIP(), []int{0}
}

func (x *GetFileSizeRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GetFileSizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileSizeResponse) Reset() {
	*x = GetFileSizeResponse{}
	mi := &file_proto_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileSizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileSizeResponse) ProtoMessage() {}

func (x *GetFileSizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileSizeResponse.ProtoReflect.Descriptor instead.
func (*GetFileSizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_proto_rawDescGZIP(), []int{1}
}

func (x *GetFileSizeResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type StreamFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Start         int64                  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	ChunkSize     int32                  `protobuf:"varint,3,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamFileRequest) Reset() {
	*x = StreamFileRequest{}
	mi := &file_proto_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFileRequest) ProtoMessage() {}

func (x *StreamFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFileRequest.ProtoReflect.Descriptor instead.
func (*StreamFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_proto_rawDescGZIP(), []int{2}
}

func (x *StreamFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *StreamFileRequest) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *StreamFileRequest) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

type StreamFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamFileResponse) Reset() {
	*x = StreamFileResponse{}
	mi := &file_proto_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFileResponse) ProtoMessage() {}

func (x *StreamFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFileResponse.ProtoReflect.Descriptor instead.
func (*StreamFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_proto_rawDescGZIP(), []int{3}
}

func (x *StreamFileResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_proto_file_proto protoreflect.FileDescriptor

const file_proto_file_proto_rawDesc = "" +
	"\n" +
	"\x10proto/file.proto\x12\x04file\"1\n" +
	"\x12GetFileSizeRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\")\n" +
	"\x13GetFileSizeResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\"e\n" +
	"\x11StreamFileRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x03R\x05start\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x03 \x01(\x05R\tchunkSize\"*\n" +
	"\x12StreamFileResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk2\x94\x01\n" +
	"\vFileService\x12B\n" +
	"\vGetFileSize\x12\x18.file.GetFileSizeRequest\x1a\x19.file.GetFileSizeResponse\x12A\n" +
	"\n" +
	"StreamFile\x12\x17.file.StreamFileRequest\x1a\x18.file.StreamFileResponse0\x01B\x12Z\x10internal/pb/fileb\x06proto3"

var (
	file_proto_file_proto_rawDescOnce sync.Once
	file_proto_file_proto_rawDescData []byte
)

func file_proto_file_proto_rawDescGZIP() []byte {
	file_proto_file_proto_rawDescOnce.Do(func() {
		file_proto_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_file_proto_rawDesc), len(file_proto_file_proto_rawDesc)))
	})
	return file_proto_file_proto_rawDescData
}

var file_proto_file_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_file_proto_goTypes = []any{
	(*GetFileSizeRequest)(nil),  // 0: file.GetFileSizeRequest
	(*GetFileSizeResponse)(nil), // 1: file.GetFileSizeResponse
	(*StreamFileRequest)(nil),   // 2: file.StreamFileRequest
	(*StreamFileResponse)(nil),  // 3: file.StreamFileResponse
}
var file_proto_file_proto_depIdxs = []int32{
	0, // 0: file.FileService.GetFileSize:input_type -> file.GetFileSizeRequest
	2, // 1: file.FileService.StreamFile:input_type -> file.StreamFileRequest
	1, // 2: file.FileService.GetFileSize:output_type -> file.GetFileSizeResponse
	3, // 3: file.FileService.StreamFile:output_type -> file.StreamFileResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_file_proto_init() }
func file_proto_file_proto_init() {
	if File_proto_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_file_proto_rawDesc), len(file_proto_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_file_proto_goTypes,
		DependencyIndexes: file_proto_file_proto_depIdxs,
		MessageInfos:      file_proto_file_proto_msgTypes,
	}.Build()
	File_proto_file_proto = out.File
	file_proto_file_proto_goTypes = nil
	file_proto_file_proto_depIdxs = nil
}
