// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: vault.proto

package vault

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VaultMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Metadata      string                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	DataType      string                 `protobuf:"bytes,6,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,7,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	UploadAt      string                 `protobuf:"bytes,8,opt,name=upload_at,json=uploadAt,proto3" json:"upload_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultMessage) Reset() {
	*x = VaultMessage{}
	mi := &file_vault_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultMessage) ProtoMessage() {}

func (x *VaultMessage) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultMessage.ProtoReflect.Descriptor instead.
func (*VaultMessage) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{0}
}

func (x *VaultMessage) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *VaultMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VaultMessage) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *VaultMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *VaultMessage) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *VaultMessage) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *VaultMessage) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *VaultMessage) GetUploadAt() string {
	if x != nil {
		return x.UploadAt
	}
	return ""
}

type VaultListMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaultObjects  []*VaultMessage        `protobuf:"bytes,1,rep,name=vault_objects,json=vaultObjects,proto3" json:"vault_objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultListMessage) Reset() {
	*x = VaultListMessage{}
	mi := &file_vault_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultListMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultListMessage) ProtoMessage() {}

func (x *VaultListMessage) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultListMessage.ProtoReflect.Descriptor instead.
func (*VaultListMessage) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{1}
}

func (x *VaultListMessage) GetVaultObjects() []*VaultMessage {
	if x != nil {
		return x.VaultObjects
	}
	return nil
}

var File_vault_proto protoreflect.FileDescriptor

const file_vault_proto_rawDesc = "" +
	"\n" +
	"\vvault.proto\x12\x05vault\"\xe1\x01\n" +
	"\fVaultMessage\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\tR\bmetadata\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x12\x1b\n" +
	"\tdata_type\x18\x06 \x01(\tR\bdataType\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\a \x01(\bR\tisDeleted\x12\x1b\n" +
	"\tupload_at\x18\b \x01(\tR\buploadAt\"L\n" +
	"\x10VaultListMessage\x128\n" +
	"\rvault_objects\x18\x01 \x03(\v2\x13.vault.VaultMessageR\fvaultObjects2M\n" +
	"\fVaultService\x12=\n" +
	"\tSyncVault\x12\x17.vault.VaultListMessage\x1a\x17.vault.VaultListMessageB\x13Z\x11internal/pb/vaultb\x06proto3"

var (
	file_vault_proto_rawDescOnce sync.Once
	file_vault_proto_rawDescData []byte
)

func file_vault_proto_rawDescGZIP() []byte {
	file_vault_proto_rawDescOnce.Do(func() {
		file_vault_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vault_proto_rawDesc), len(file_vault_proto_rawDesc)))
	})
	return file_vault_proto_rawDescData
}

var file_vault_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vault_proto_goTypes = []any{
	(*VaultMessage)(nil),     // 0: vault.VaultMessage
	(*VaultListMessage)(nil), // 1: vault.VaultListMessage
}
var file_vault_proto_depIdxs = []int32{
	0, // 0: vault.VaultListMessage.vault_objects:type_name -> vault.VaultMessage
	1, // 1: vault.VaultService.SyncVault:input_type -> vault.VaultListMessage
	1, // 2: vault.VaultService.SyncVault:output_type -> vault.VaultListMessage
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vault_proto_init() }
func file_vault_proto_init() {
	if File_vault_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vault_proto_rawDesc), len(file_vault_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vault_proto_goTypes,
		DependencyIndexes: file_vault_proto_depIdxs,
		MessageInfos:      file_vault_proto_msgTypes,
	}.Build()
	File_vault_proto = out.File
	file_vault_proto_goTypes = nil
	file_vault_proto_depIdxs = nil
}
